import ContributionsDisplay from "@/components/ContributionsDisplay";
import { getContributions as ghGet } from "@/utils/gh-queries";
import { AcceptedEntries } from "@/utils/helpers";
import type { InferGetServerSidePropsType } from "next";
import Head from "next/head";

export const getServerSideProps = async () => {
  const githubDetails = {
    ...(await ghGet("ickynavigator")),
    type: AcceptedEntries.Github
  };

  return {
    props: {
      details: [githubDetails]
    }
  };
};

export default function Home(
  props: InferGetServerSidePropsType<typeof getServerSideProps>
) {
  const { details } = props;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ContributionsDisplay entries={details} />
    </>
  );
}
